### PR TITLE
FirefoxProfile into FirefoxPreferences

### PR DESCRIPTION
**Pull request by audioXD**
Renamed ReforefoxProfile into FirefoxPreferences,
Changed to work like Capabilities,
Added helper methods,

Without doc comments

#56

### CODE REVIEW

**Comment by audioXD** [comment]
This is a breaking change so the version should be updated.

**Comment by audioXD** [comment]
Added the docs and made some other changes

**Comment by audioXD** [comment]
I'm not sure if it sould be named `reset` or `unset`

**Comment by stevepryde** [comment]
> I'm not sure if it sould be named `reset` or `unset`

I like unset better

**Review by stevepryde — APPROVED** [review]

**Pull request merged**
