### PR TITLE
Resolve webdriver api paths relative to server_url

### PR DESCRIPTION
**Pull request by grelner**
Sorry for the delay, but here is a fix for #229. 
Thirtyfour uses Url::join to resolve url's with an argument that starts with '/'. Given webdriver url "http://localhost:4444/wd/hub" and "/session", Url::join will return http://localhost:4444/session, thus making is incompatible with systems such as selenoid, and selenium versions < 4 which use /wd/hub as a base path.
This PR simply removes the leading slash from the selenium api paths and this makes Url::join resolve the paths as expected.

### CODE REVIEW

**Review by vrtgs — CHANGES_REQUESTED** [review]
when you use `impl AsRef<_>` in a function it adds a silent generic, which makes it so the function will be monomorphized for every type of path, this is esspecially bad for async fn and has bigger impact on compile times, as every invocation now has its own complicated state machine

so I would suggest doing what the stdlib already does with things like std::fs::write:
```rs
fn foo(p: impl AsRef<Path>) {
    fn inner(path: &Path) {
        /*code*/
    }
    inner(p.as_ref())
}
```

**Comment by vrtgs** [comment]
hey I hope you aren't busy but I'm just checking to make sure you see this, so could you implement the changes or should I pull them in then change them my self?

**Comment by grelner** [comment]
Hi sorry this fell between the cracks. I've reverted the AsRef<Path> commit, as it's not relevant to this PR

**Review by vrtgs — DISMISSED** [review]
lgtm

**Review by vrtgs — APPROVED** [review]

**Comment by grelner** [comment]
@Vrtgs not sure I understand that coverage test failure. I don't see any failures in the log

**Pull request merged**
